language: python
python: 3.8

os:
  - linux
  dist: bionic
  - osx
  - windows

jobs:
  allow_failures:
    - os: windows


compiler:
  - gcc

git:
  depth: 1

install:
  - pip install -r requirements.txt

script:
  - make test
